import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";

// Geist Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Poppins Font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // choose what you need
});

export const metadata: Metadata = {
  title: "Iqra Rafiq Khan",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/Logo-Light.svg", type: "image/svg+xml", media: "(prefers-color-scheme: dark)" },
      { url: "/Logo-Dark.svg", type: "image/svg+xml", media: "(prefers-color-scheme: light)" },
    ],
  },
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <div className="bg-background">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
